#! /usr/bin/python

import urllib, urllib2, sys

if len(sys.argv) == 2:
	with open(sys.argv[1], "r") as file:

		name = sys.argv[1]

		if name.find("/") != -1:
			name = name[::-1]	
			name = name[:name.find("/")]
			name = name[::-1]	
		
		data = file.read()
	
		url = "http://128.113.192.63/loadFile.php"
		values = dict(name=name, data=data)
		data = urllib.urlencode(values)
		
		try:
			request = urllib2.Request(url, data)
			response = urllib2.urlopen(request)
		except:
			print "Error."
		
		
		if ("Success" in response.read()):
			print ("Success")
	
		else:
			print "Error"
else:
	print "Please include filename."	
